### ISSUE TITLE
unorm

### ISSUE THREAD

**Issue by tomitrescak** [odysseyscience/react-s3-uploader#104]
Hi, `unorm` is a nice little library, yet it has 140kb, 40kb gzipped. That is massive. Would you consider switching to something more lightweight? And thanks for the great package!

**Comment by seanadkinson** [comment]
Yeah, that's massive and embarrassing.  I didn't personally add the dependency, but merged a PR that did.  It's pretty silly for it to be that large.

Most of the issues we get on this repo are about file names with unexpected characters, and there has been a lot of churn.  I'd absolutely be happy to add a breaking change that simplifies this greatly, and removes all the dependencies.  I think something simple such as `filename.replace(/[^\w]/g, '')` would be a fine default behavior, and then add the ability to provide your own replacer function for people that want more.

I just don't think I'll get to this soon with my current workload, but I'm happy to merge a breaking PR if you or someone else sees this and wants to implement that.

Thanks for your feedback though!

**Comment by seanadkinson** [comment]
Released `v4.0.0` with some changes from your PR.  Thanks for that!

I changed the code to have a default `scrubFilename` function, which can be overridden to provide different behavior.  Also removed the `latinize` dependency.
