### ISSUE TITLE
Custom "submit" button

### ISSUE THREAD

**Issue by sniepoort** [odysseyscience/react-s3-uploader#107]
I think it would be great if you first can choose your files, and then press a button that starts uploading (which would also give the possibility of a nice custom "Upload images" button). Is there any solution for this?

**Comment by seanadkinson** [comment]
This repo just renders an `<input>`, but if we get the non-auto start functionality in there (I saw your comment on #95) then it would be pretty easy to render your button elsewhere, and call `uploadFile()` on the `ReactS3Uploader` component.  I think just adding a few opt-in behaviors should make this work pretty simply.  I'll see what I can do, or look at any PRs if you or someone else wants to take a stab.

**Comment by shmargum** [comment]
If you wrap the input in a `<label>` and click the label it will trigger the input
you can add a custom component inside the label and hide the input
you can use the `preprocess(file, next)` function to intercept the click and do things then trigger the file upload by calling `next(file)`
`
<label>
  <CustomComponent />
  <ReactS3Uploader style={{display: 'none'}} preprocess={(file, next) => {...; next(file)} }/>
</label>
`

**Comment by oyeanuj** [comment]
@seanadkinson along with providing a non auto-start functionality, would you consider non-render-input toggle as well in which case the developer has to call the same `uploadFile` method with the actual file?

This would be super useful where you want to use this component in parallel with an existing file upload setup, like in my case, where only certain file types need to go to S3.

**Comment by seanadkinson** [comment]
@oyeanuj If that is a configuration change you'd like, and want to submit a PR for, I'd be happy to merge and release, as long as we stay backward compatible.  Thanks!

**Comment by divan** [comment]
I'm using my own component that allows cropping/resizing and returns Blob with image. Any chance to use it with `react-s3-uploader`?

**Comment by arvinsim** [comment]
Any progress on this feature request?

**Comment by LKozakewycz** [comment]
@arvinsim I've submitted a PR for disabling autoUpload #155 

See https://github.com/odysseyscience/react-s3-uploader/issues/95#issuecomment-348938802

**Comment by seanadkinson** [comment]
Can be supported now with `autoUpload={false}` in `v4.6.0` and a custom button.  (See @LKozakewycz above).
