### ISSUE TITLE
Is there any way to upload files programmatically?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [odysseyscience/react-s3-uploader#109]
I got a webRTC recorded video from camera. 
I want to be able to upload it to s3. But I don't need input field. Cause file is generated on client side.
I can make component invisible and create events manually, but it's kinda not cool. And is there a method to start upload manually, not when file got selected?

![screen shot 2017-02-11 at 20 00 23](https://cloud.githubusercontent.com/assets/4464561/22855639/cbf38bf6-f094-11e6-8100-a297006412f5.png)

**Comment by seanadkinson** [comment]
You could use the `s3upload.js` part separately if you like.  Just import `react-s3-upload/s3upload`, and do `new S3Upload({ file: myFile })` I believe.  Might require a little more mangling, but it should work okay.

Reopen if you need more help/guidance.

**Comment by Blah237** [comment]
Struggling with this. I'm getting a blob from react-image-crop and then want to upload it to S3. Do you have an example of how this might be done?
