### ISSUE TITLE
Headers not signed

### ISSUE THREAD

**Issue by waclock** [odysseyscience/react-s3-uploader#110]
Hello,

I'm having an issue while trying to upload an image. This is the error I get when I try uploading a file:

```<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not  @signed</Message><HeadersNotSigned>x-amz-acl</HeadersNotSigned><RequestId>```

However these are my CORS rules, and I'm accepting all kind of headers (I've also tried just with that kind of header)

```<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

Any help is appreciated.

**Comment by seanadkinson** [comment]
Seems to be an issue with the request signing, not your configuration.  How are you signing the request URL?

**Comment by waclock** [comment]
I was signing the URL in a RoR server. Basically this was the code:

`presigner = Aws::S3::Presigner.new
          url = presigner.presigned_url(:put_object, #method
                                  bucket: ENV['AWS_BUCKET_NAME'], #name of the bucket
                                  key: ENV['AWS_WEBAPP_FOLDER']+"/"+params[:file_name], #key name
                                  acl: 'public-read', #privacy
                                  expires_in: 5.minutes.to_i #time should be in seconds
                                  ).to_s`

I ended up adding `acl: 'public-read'` on the server and removing ACL from my client. Everything's working now.

**Comment by seanadkinson** [comment]
👍
