### ISSUE TITLE
Option to drop the UUID from filenames

### ISSUE THREAD

**Issue by juusaw** [odysseyscience/react-s3-uploader#111]
I have a use case where I need the filename in S3 to match the original. As far as I know, this is currently not possible with the library as the signing endpoint prepends the filename with UUID. Is there currently a way to bypass this? If not, would it be ok to implement an option to do so?

**Comment by juusaw** [comment]
Pull request #112 resolves this.

**Comment by seanadkinson** [comment]
Pushed `v4.0.2` with this change.  Thanks

**Comment by CobySoffer** [comment]
Thank you!
