### ISSUE TITLE
Files ALWAYS get unique prefix

### ISSUE THREAD

**Issue by tomitrescak** [odysseyscience/react-s3-uploader#113]
When I set { uniquePrefix: false } nothing happens, files always get the prefix ;(

app.use('/s3', require('react-s3-uploader/s3router')({
    bucket: '--',
    uniquePrefix: false,
    region: '--', 
    signatureVersion: 'v4', 
    headers: { 'Access-Control-Allow-Origin': '*' }, 
    getFileKeyDir: function (req: any) {
      return req.headers['folder'];
    }
  }));

**Comment by tomitrescak** [comment]
Nevermind .. was runnin 4.0.1

**Comment by seanadkinson** [comment]
👍 Let me know if you have any other issues.  Thanks

**Comment by seanadkinson** [comment]
Added note in readme where that param is documented.
