### ISSUE TITLE
React 15.5 deprecations - PropTypes and CreateClass

### ISSUE THREAD

**Issue by kusold** [odysseyscience/react-s3-uploader#116]
![screen shot 2017-04-24 at 3 15 43 pm](https://cloud.githubusercontent.com/assets/509966/25359064/f097336e-2900-11e7-8680-c710888c0daa.png)

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by seanadkinson** [comment]
Published `v4.1.0` with your PR.  Thanks 👍
