### ISSUE TITLE
Undefined variable storage

### ISSUE THREAD

**Issue by amonetti** [odysseyscience/react-s3-uploader#121]
Hi,

I defined fog.rb in config/initializers as follow:

```
storage = Fog::Storage.new(
  provider: 'AWS',
  aws_access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
)

```
Then in the controller:
```
options = {path_style: true}
        headers = {"Content-Type" => params[:contentType], "x-amz-acl" => "public-read"}
        url = storage.put_object_url(ENV['S3_BUCKET_NAME'], "user_uploads/#{params[:objectName]}", 15.minutes.from_now.to_time.to_i, headers, options)

```
I am getting the following error:
` undefined local variable or method 'storage' `

Can you help me?
Thanks

**Comment by seanadkinson** [comment]
Sorry, I didn't provide the documentation for RoR, and don't really know the environment well.  But if you declare a local variable `storage` in one file, I wouldn't expect it to be accessible in a separate file, your controller in this case.  Is RoR supposed to "magic" that together?  Your error is clearly just that the `storage` variable is not available in the controller.  Maybe move it out of `initializers`, and into the controller, just to verify?

**Comment by amonetti** [comment]
I changed storage by ::Storage in the initializer and then in the controller Storage.put_object_url(...) and it works. 

Thanks!
