### ISSUE TITLE
ref prop

### ISSUE THREAD

**Issue by eelsweb** [odysseyscience/react-s3-uploader#123]
React provides a nice way to get a reference to the DOM element using `ref`

[Refs and the DOM](https://facebook.github.io/react/docs/refs-and-the-dom.html)

If I try to do something like this - 

```
<ReactS3Uploader
	accept = 'image/*'
	... // more props
	ref={this.handleRef}
/>

```
then I just get a constructor of this component rather than the DOM element.

Is there some way to get the final DOM element dynamically ? I need it to manually focus on the upload button.

**Comment by bmatto** [comment]
Did you ever find a way to do this?

**Comment by seanadkinson** [comment]
`inputRef` is now available for this.

**Comment by bmatto** [comment]
🍺
