### ISSUE TITLE
Is there some way to add a custom path in an s3 bucket (e.g. s3:mybucket/custompath/file.jpg)? 

### ISSUE THREAD

**Issue by vgracia** [odysseyscience/react-s3-uploader#124]
So yeah,   I would like to put all files into a sub-directory of a bucket.  Possible here?  

Thanks!

**Comment by seanadkinson** [comment]
Assuming you are using the express router, you can pass in a `getFileKeyDir` function, which is given the `req`, and can return a prefix for the S3 key.  Not well documented, but see [here](https://github.com/odysseyscience/react-s3-uploader/blob/master/s3router.js#L17)

Let me know if you have any issues with that.
