### ISSUE TITLE
Multipart upload with presigned url

### ISSUE THREAD

**Issue by oyeanuj** [odysseyscience/react-s3-uploader#125]
Hi @seanadkinson, thank you for the library! 

I was wondering if you think adding support for multipart upload using [S3 Managed Uploader](https://aws.amazon.com/blogs/developer/announcing-the-amazon-s3-managed-uploader-in-the-aws-sdk-for-javascript/) (while using presigned urls) makes sense for the library?

**Comment by seanadkinson** [comment]
I think it makes perfect sense to be able to utilize the new uploading capabilities.  Not sure how much work it would be, but if you want to give it a try, I'd be happy to take a look and merge if good.
