### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by veekram** [odysseyscience/react-s3-uploader#142]
I have been trying to upload an image file to S3 bucket with signing key provided by Ruby. As per documentation, I have following in my controller: 

```
class AwsUploadsController < ApplicationController
    def signing_url
      storage = Fog::Storage.new(
        provider: 'AWS',
        aws_access_key_id: ENV['AWS_KEY'],
        aws_secret_access_key: ENV['AWS_SECRET']
      )

      options = {path_style: true}
      headers = {"Content-Type" => params[:contentType], "x-amz-acl" => "public-read"}

      url = storage.put_object_url(ENV['S3_BUCKET'], "#{ENV['S3_FOLDER']}/#{params[:objectName]}", 15.minutes.from_now.to_time.to_i, headers, options)

      respond_to do |format|
        format.json { render json: {signedUrl: url} }
      end
    end
  end
```

Below is how I try to upload file from react side.
`<ReactS3Uploader
      signingUrl="http://localhost:3020/signing_url"
      accept="image/*"
   />`

All all my luck, I have been getting the following error:
This is from the browser console log.
```
Pre-process: Screen Shot 2017-09-08 at 11.36.20 AM.png
Upload progress: 0% Waiting
Upload error: Invalid response from server
```

From the signed url I have got, I get:
```
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

The CORS configuration for S3 is:
```
<!-- Sample policy -->
<CORSConfiguration>
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>PUT</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>*</AllowedHeader>
	</CORSRule>
</CORSConfiguration>
```

Surely, seems like I have been missing something , which is throwing me with error:
```
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Thanks, any help is appreciated.

**Comment by seanadkinson** [comment]
Hi there,

I didn't contribute the documentation for the ruby server, so I'm not really sure what the problem could be on your server-side.  What I would do is try to take the s3-uploader client code out of the picture, and make sure your signed URL is working.

So for example, you might try the following steps:

Using `curl` or PostMan:
* Make a request to your server to generate a signed url
* Use that URL to `PUT` a file on S3
* If it works, use Chrome tools to understand why the requests aren't matching what worked
* If it doesn't work, change/debug without s3-uploader until it is working

Hope that helps.  Please respond with any additional questions, insights, or solutions.  Good luck!

**Comment by veekram** [comment]
Thank you @seanadkinson. Let me go through what you have told. Cheers!
