### ISSUE TITLE
Request: instructions for use with Digital Ocean Spaces

### ISSUE THREAD

**Issue by shankie-san** [odysseyscience/react-s3-uploader#146]
The new DO Spaces service claims to have the same API as S3; however, I'm having some trouble getting things working.

I've gotten somewhere using Express code like this:

```js
const EP = new AWS.Endpoint('nyc3.digitaloceanspaces.com');

app.use(
  "/s3",
  require("react-s3-uploader/s3router")({
    bucket: "my-bucket", // From my-bucket.nyc3.digitaloceanspaces.com
    getS3: () =>
      new AWS.S3({ endpoint: EP, params: { Bucket: "proper-public" } }),
    headers: { "Access-Control-Allow-Origin": "*" },
    ACL: "public-read",
    uniquePrefix: true
  })
);
```

I can successfully get a signing URL, but in the browser, when I attempt to upload a file to the signed URL, the `OPTIONS` request gets a 403 – in addition to a CORS error. However, taking the signed URL and manually doing a `PUT` with Postman works.

This suggests to me that it's something wrong with the configuration on the client, not the signed URL.

Perhaps it's something like the DO request doesn't support the pre-flight request?

At any rate, if anyone has any ideas, post here. I'll do the same. In the meantime, I might fork this repo and see if I can work out how to selectively disable the pre-flight request.

**Comment by seanadkinson** [comment]
Sounds like a CORS issue.  I'm not familiar with DO Spaces, but you should see if there is some way to configure CORS on their end, to allow requests from your website domain.  S3 has this concept as well, so I'd expect DO to have it.

**Comment by shankie-san** [comment]
It looks like you're right @seanadkinson . I think that for the minute, the default is "All Origins", so the pre-flight request fails. It looks like they do support CORS rules, but don't have a UI for it at the moment – see [here](https://www.digitalocean.com/community/questions/how-to-restrict-object-access-to-only-certain-origins-through-cors-policy-in-spaces). 

Probably biting off more than I can chew at the moment so have just switched to AWS for now (and have it working – no thanks to Amazon's UI!), but will see if I can come back to this in the future.

Thanks for your help, closing.

**Comment by jgannondo** [comment]
@shankie-san We are working on a UI for CORS which we are hoping to ship in the next couple of weeks. And yes, CORS configuration can be set via the Spaces API in the interim.

**Comment by shankie-san** [comment]
Ah that's great, thanks @jgannondo !
