### ISSUE TITLE
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

### ISSUE THREAD

**Issue by e-monson** [odysseyscience/react-s3-uploader#15]
I'm unable to retrieve the CORS permissions from my bucket because the signed URL that the router generates is of the form https://s3.amazonaws.com/example/blahblah..., but my bucket responds with an error message telling me to use an address like https://example.s3.amazonaws.com/blahblah... Is there some way to change the the way the router generates the URL?

**Comment by e-monson** [comment]
Sorry if my wording is confusing. A very similar situation is referenced in this issue from another project, if that helps: https://github.com/waynehoover/s3_direct_upload/issues/30

**Comment by seanadkinson** [comment]
Hmmm, the relevant section of code is this:

        var s3 = new aws.S3();
        var params = { Bucket: S3_BUCKET, ... };
        s3.getSignedUrl('putObject', params, function(err, data) {
            ...
        });

So we aren't doing anything special.  Maybe there is an option to tell `aws.S3` to construct the URL differently?  If so, maybe you can put up a PR and I'll throw up another release.  Otherwise I'll try to look at this more in the next few days.

**Comment by e-monson** [comment]
Thanks for the quick response. I'll look into getSignedUrl and see what I can do.

**Comment by tylercollier** [comment]
For me it turned out to be not specifying the region. This is of course confusing since when you are in the S3 management console, it says "S3 does not require region selection". I guessed at my region of us-west-2, but anyone reading this could theoretically have a different one I guess.

```
app.use('/s3', S3Router({
  region: 'us-west-2',
})
```
