### ISSUE TITLE
Put request access denied in production app, but not in development

### ISSUE THREAD

**Issue by natashache** [odysseyscience/react-s3-uploader#158]
The uploader is working fine when I run my app on localhost. But once it moves to the production server, I get '403' error from s3 that says 'access denied'
![screenshot 2017-12-25 16 51 19](https://user-images.githubusercontent.com/19754530/34343171-4d6fb63e-e994-11e7-8757-c2dde3ef9f9d.png)

My cors configuration for the s3 budget seems normal

![screenshot 2017-12-25 16 55 11](https://user-images.githubusercontent.com/19754530/34343179-75ababf8-e994-11e7-93cd-2bd7b3b6874d.png)

Here's my server side code:
```
AWS.config.update(awsConfig);
app.use('/s3', require('react-s3-uploader/s3router')({
  bucket: 'budget_name',
  headers: {'Access-Control-Allow-Origin': '*'}, // optional
  ACL: 'public-read',
  getFileKeyDir: function(req) {
      return 'users/';
  },
  uniquePrefix: false, 
}));
```
Here's the client side code:
```
                                    <ReactS3Uploader
                                        signingUrl="/s3/sign"
                                        signingUrlMethod="GET"
                                        accept='.mp3,.m4a'
                                        preprocess={this.preProcess.bind(this)}
                                        onProgress={this.onProgress.bind(this)}
                                        onError={this.onError.bind(this)}
                                        onFinish={this.onFinish.bind(this)}
                                        uploadRequestHeaders={{ 'x-amz-acl': 'public-read' }}  
                                        contentDisposition="auto"
                                        scrubFilename={(filename) => {
                                            const original = filename.split('.');
                                            const newName = that.episodeId;
                                            return filename.replace(filename.slice(0), `${newName}.${original[original.length -1]}`);
                                        }}
                                        inputRef={cmp => this.uploadAudioInput = cmp}
                                        autoUpload={true}
                                        />
```
If I add the 'server' prop to `ReactS3Uploader` (`server="https://production-server.com"`), to assign the server as the production server I use, and run the app locally, I get the same error. I suppose that means 'react-s3-uploader/s3router' works on my localhost but somehow is having a glitch on my production server.

Any idea why this is happening?

**Comment by natashache** [comment]
@seanadkinson any suggestions?

**Comment by natashache** [comment]
Solved this for now by increasing the expiration period in `s3router.js` from 60 secs to 300:
```
        var params = {
            Bucket: S3_BUCKET,
            Key: fileKey,
            Expires: 300, //originally 60
            ContentType: mimeType,
            ACL: options.ACL || 'private'
        };
```
Not sure if this is a good practice. Seems rather hacky.

**Comment by seanadkinson** [comment]
Hmm, that is odd.  Seems like you may have a timezone issue, but I'm not sure.  I believe all AWS is configured with UTC time.  Does your production server have a non-UTC timezone by chance?  Worth looking into, but yeah, seems flaky and hacky.

**Comment by kliu4** [comment]
Probably your server is not synced with the `ntp` servers. You could check the difference of your server time and current time. If it has some differences (I guess there are some seconds' difference), install `ntpd` to sync time.

**Comment by seanadkinson** [comment]
Going to close for now, but let me know if you need more guidance.  Thanks

**Comment by davinpalmtreenft** [comment]
First off, thanks a ton for this really useful package!

I am experiencing similar behavior where I can successfully upload images from my app's front end while the back end is running locally however when I try through my deployed back end I receive an ominous `message: "Forbidden"`.

Here is my front end code:
```
        <ReactS3Uploader
          signingUrl="/s3/sign"
          signingUrlMethod="GET"
          accept="image/*"
          s3path="/uploads/"
          onFinish={(res) => {
            setUploadUrl(
              process.env.NEXT_PUBLIC_AWS_API_GATEWAY_URL + res.publicUrl
            );
          }}
          uploadRequestHeaders={{ 'x-amz-acl': 'private' }} // this is the default
          contentDisposition="auto"
          scrubFilename={(filename) => filename.replace(/[^\w\d_\-.]+/gi, '')}
          server={process.env.NEXT_PUBLIC_AWS_API_GATEWAY_URL}
          autoUpload={true}
          className="border p-1"
        />
```

Here is my back end code:
```
app.use(
  '/s3',
  require('react-s3-uploader/s3router')({
    bucket: '<bucket_name>',
    signatureExpires: 60, // optional, number of seconds the upload signed URL should be valid for (defaults to 60)
    ACL: 'private', // this is default
    uniquePrefix: true, // (4.0.2 and above) default is true, setting the attribute to false preserves the original filename in S3
  })
);
```

And here are the response headers that I receive when the client tries to retrieve the signedUrl:

![image](https://user-images.githubusercontent.com/111806715/223575806-8c74b66a-1f73-4a0a-92ac-535a01cf1056.png)

I have tried adding various bucket policies including one that is almost wide open, s3 permissions to my lambda function (backend is api gateway with lambda function) and adjusting the signatureExpires value as mentioned above.

Been banging my head against a wall for a while on this one, would really appreciate any help or ideas.  Would even be willing to offer a bounty/donation to get it sorted.  

Thanks in advance for any attention.
