### ISSUE TITLE
Breaking change in v4.4.0 causes filenames generated with undefined in them

### ISSUE THREAD

**Issue by saxbophone** [odysseyscience/react-s3-uploader#160]
If I understand it correctly, according to the changes introduced in v4.4.0 (https://github.com/odysseyscience/react-s3-uploader/compare/v4.3.0...v4.4.0), a new mandatory prop was added, `s3path`.

We started using this dependency for one of our projects around v4.0.2, before this parameter existed. We had the version pinned to the v4.x.x range and when it was updated, it introduced a bug where newly-uploaded files had filenames generated of the form `<uuid>_undefined<file name>`.

By taking a look at the code diff between these versions of this library, it seems that `s3path` is being set to a blank string by default, however it appears to be `undefined` at the point that the filename/path is generated.

As a workaround, we have pinned the version of the library we're using to v4.3.0 for now.

The most common-sense solution I can think of would be to only include `s3path` in the final filename if it's _truthy_, using appropriate logic. Having the ability to specify an additional directory prefix to store files under seems like it ought to be an optional, not a mandatory feature.

**Comment by seanadkinson** [comment]
Absolutely should not be mandatory.  Thanks for reporting this.

Looks like this was introduced with the last PR: #156

Will push a fix.

**Comment by seanadkinson** [comment]
Fixed in version 4.6.2.  Can you give it a try?  Thanks

**Comment by saxbophone** [comment]
Thanks for your most speedy reaction! 😃 

I will test out the fix now, stay tuned...

**Comment by saxbophone** [comment]
Yay! It's all fixed now. You're very welcome for the report, thanks again for fixing it so quickly 👌 👍
