### ISSUE TITLE
Mid-upload error? Any ideas?

### ISSUE THREAD

**Issue by Siyfion** [odysseyscience/react-s3-uploader#161]
After uploading an image of around 6MB, I get the following output:

![screen shot 2018-01-09 at 13 11 26](https://user-images.githubusercontent.com/338488/34722454-e7cdc5bc-f53e-11e7-9349-c2cd39fbfa31.png)

Clearly you can see that an ERR_CONNECTION_RESET error is thrown, but I was wondering if you might have any suggestions as to why!? I've implemented my own pre-signed URL endpoint which had an expiry set for 20 seconds, but to rule that out I set it to an hour and it made no difference.

**Comment by Siyfion** [comment]
I think it might have been something to do with my IAM role not having PutObjectAcl permissions. Either way, it's working now.

**Comment by willian** [comment]
@Siyfion can you elaborate more about the solution you found?
I am having the same issue, sometimes it returns `net::ERR_FAILED` as well.
I checked my IAM and it has full S3 access. The CORS for the bucket is configured. And I didn't add any Bucket Policy configured.

**Comment by willian** [comment]
No problem! Thanks, anyway!

**Comment by Scottjutsu** [comment]
@willian did you happen to find a solution?
