### ISSUE TITLE
Support for multiple file upload?

### ISSUE THREAD

**Issue by neqsoft** [odysseyscience/react-s3-uploader#166]
> Does this work with multiple file upload? 

Let's say I want to allow the user to select 1+ files on a single "browse files" operation. Is that possible? And if it is, is there any example of doing it?

Thanks!

**Comment by seanadkinson** [comment]
I think it just works the same as you would normally allow for multiple files to be selected.  That is, you should just be able to add `multiple` as a prop to the element.  This library proxies all unknown attributes down to the rendered `<input type="file"/>`, so add `multiple`, and you should be able to select multiple files.

Please feel free to submit a PR with some documentation updates if you find a good solution and example of your usage.  Let me know if it does or doesn't work (I don't currently use this library anymore, I just help maintain it).  Re-open if you need more guidance. Thanks!

**Comment by iamrahulroy** [comment]
@seanadkinson I encountered a weird issue with `multiple` attribute. I have array of files stored in the parent state to display progress bar. When multiple files are selected, it only renders one file. 

Moving state update logic inside setTimeout solves the issue.

```
getSignedUrl(file, callback) {
  // ReactS3Uploader has a bug for multiple file select
  setTimeout(() => {
    // ...

    this.setState({
      uploadStatuses: [...this.state.uploadStatuses, uploadedItemDetail]
    })

    // ...
  }, 0)
}
```

The same function is being used for folder upload using `react-dropzone` & `s3upload.js` and it was working fine without using setTimeout function. Any idea why?
