### ISSUE TITLE
way to Abort current uploading?

### ISSUE THREAD

**Issue by harvinder-ss** [odysseyscience/react-s3-uploader#167]
Hi, I have a situation where I want the user to abort the  abort the current uploading file. Is there any way to do this in this component ? 

Appreciate your quick response!

Thanks.

**Comment by harvinder-ss** [comment]
Just to be more clear, I need way to cancel the current upload after it has started and may be 50% or 90% uploaded to s3.

**Comment by seanadkinson** [comment]
@harvinder-ss There exists an [abort method](https://github.com/odysseyscience/react-s3-uploader/blob/master/ReactS3Uploader.js#L84) that you can call if you save off a `ref` of the component.  You'll need to bring your own UI though, as this library only renders an `<input type="file"/>`.  Re-open if you need more guidance.

**Comment by harvinder-ss** [comment]
Thanks for your response. I have done it already using the same way. :)
