### ISSUE TITLE
this.onSignedUrl is not a function

### ISSUE THREAD

**Issue by zjr** [odysseyscience/react-s3-uploader#172]
I don't have much time to look into this but I have been getting a `this.onSignedUrl is not a function` error in `v4.7.0`, looks likely related to #170, though, I think I see there's a default prop(?). Stepping down to previous version fixes.

Here is the stack (not very useful but here it is anyway):
```
TypeError: this.onSignedUrl is not a function
    at S3Upload.<anonymous> (http://localhost:1350/app.js:37535:22)
```

Here is our use of the component:
```jsx
<ReactS3Uploader
  accept="image/*"
  onError={this.onUploadError}
  onFinish={this.onUploadFinish}
  onProgress={this.onUploadProgress}
  signingUrl="/s3/dash/media/sign"
  ref={input => (this.s3Uploader = input)}
  style={{ display: 'none' }}
/>
```

To help make up for the lacking stack trace… this happens in `S3Upload.prototype.executeOnSignedUrl`, looks like L107, in `xhr.onreadystatechange()`.

**Comment by seanadkinson** [comment]
Hmmm, I can't see any reason why `this.onSignedUrl` would not be a function, but clearly if you are getting this error, something is wrong.

Looks like that last PR didn't add to the prototype of `s3upload`, so i'll add a base implementation there, like some of the other handlers.

**Comment by seanadkinson** [comment]
Pushed `v4.7.1` with this change.  Re-open if you still see the issue.
