### ISSUE TITLE
react-s3-uploader stopped working without any code changes and isn't throwing any error

### ISSUE THREAD

**Issue by jignesh248** [odysseyscience/react-s3-uploader#183]
I haven't made any changes that should affect my upload , all my event functions has console.logs and also all the variables values are available in console.logs in render method, yet I am not sure why it stopped working. NO API calls, NO console errors, No console logs from events methods, it is failing silently and I have no idea why. I also tried manual upload but with a button with onClick={()=>this.uploadInput.uploadFile()}, but even that fails without error.

Anybody elsed faced such issue???

<ReactS3Uploader
className="profile_image"
                                            signingUrl={"s3/sign"}
                                            signingUrlMethod="GET"
                                            accept="image/*"
                                            s3path={"uploads/"+SomeVar+"/"}
                                            preprocess={this.onUploadStart.bind(this,'ImageName')}
                                            onProgress={this.onUploadProgress.bind(this,'ImageName')}
                                            onError={this.onUploadError.bind(this,'ImageName')}
                                            onFinish={this.onUploadFinish.bind(this,'ImageName')}
                                            signingUrlHeaders={{"x-access-token": this.props.cookies?this.props.cookies.token:""}}
                                            //signingUrlQueryParams={{ additional: query-params }}
                                            //signingUrlWithCredentials={ true }      // in case when need to pass authentication credentials via CORS
                                            uploadRequestHeaders={{ 'x-amz-acl': 'public-read' }}  // this is the default
                                            contentDisposition="auto"
                                            scrubFilename={(filename) => filename.replace(/[^\w\d_\-.]+/ig, '')}
                                            server={process.env.API_SERVER}
                                            inputRef={cmp => this.uploadInput = cmp}
                                            autoUpload={true}
                                        />

**Comment by seanadkinson** [comment]
Seems likely to be an issue outside the control of this code.  Have you determined if you can sign and upload a file using curl or postman?  That would be my first recommendation.

**Comment by jignesh248** [comment]
My bad, my coworker added Google Tag Manager script as is and not something ported for react that doesn't interfere with react events, react virtual DOM-real DOM bindings, I removed it and it works fine now.
