### ISSUE TITLE
can we get the duration of audio/video file?

### ISSUE THREAD

**Issue by harvinder-ss** [odysseyscience/react-s3-uploader#185]
can we get the duration of audio/video file while trying to upload it using the preprocess function? I dont want my users to upload very long audio files.. is there any way?

Thanks

**Comment by seanadkinson** [comment]
Hmmm, not sure.  Certainly outside the scope of this library, so if you come up with something, feel free to reply here, but will close for now, as this is not really a question about `react-s3-uploader`.  Good luck!
