### ISSUE TITLE
How to get the current file name in  onProgress in case of Multiple File Upload ?

### ISSUE THREAD

**Issue by naxir** [odysseyscience/react-s3-uploader#186]

**Comment by naxir** [comment]
onProgress: function(percent, message , file) {
                console.log('Upload progress: ' + percent + '% ' + message);
            },

is this is possible by passing file parameter ?

**Comment by seanadkinson** [comment]
Third argument to `onProgress` is the `file`.  I believe it has a `name` property`.  Can you check and confirm?  Thanks!

**Comment by naxir** [comment]
@seanadkinson I have checked the Repo Code of ReactS3Uploader.js we have to pass third argument i.e file to get the filename in getDefaultProps function() { }

correct me if i am worng 
Thanks
onProgress: function(percent, message) {
                console.log('Upload progress: ' + percent + '% ' + message);
            },
