### ISSUE TITLE
Using pre-signed url.

### ISSUE THREAD

**Issue by chakrit** [odysseyscience/react-s3-uploader#22]
Is there a way to use this with pre-signed URL already available?

**Comment by seanadkinson** [comment]
Not currently written to support that case, but (this line)[https://github.com/odysseyscience/react-s3-uploader/blob/master/s3upload.js#L135] would just need to be skipped if you already have the `signResult`.  Shouldn't be too hard to add.  Maybe you can try it out and submit a PR?

**Comment by jakubrohleder** [comment]
Actually I also need this feature and would love to make the PR. I recon the code has changed since the issue has been created. @seanadkinson can you give me some tips on implementing it in the current project state?

**Comment by jakubrohleder** [comment]
In fact I've just analyse the code an prepared a small PR that solves this issue.

**Comment by seanadkinson** [comment]
In `v3.2.0`, you can now provide `getSignedUrl()` with the proper object, and pass your pre-signed URL.
