### ISSUE TITLE
Content-Type is blank when uploading

### ISSUE THREAD

**Issue by dobesv** [odysseyscience/react-s3-uploader#223]
Sometimes when uploading a file, the content-type is set blank.  Is there a simple way to set this to a default value for that header if the `file.type` is not provided?

![image](https://user-images.githubusercontent.com/327833/97364230-f74edd80-1860-11eb-8e41-7df92776dd84.png)

**Comment by dobesv** [comment]
I think I'll change the URL signing system so that it returns `Content-Type` in the headers as a workaround.

**Comment by seanadkinson** [comment]
Merges a fallback to `mime-type` lookup.  Thanks for reporting!

**Comment by seanadkinson** [comment]
Published `v5.0.0` with this fix
