### ISSUE TITLE
How to notify server of image upload?

### ISSUE THREAD

**Issue by pmazumder3927** [odysseyscience/react-s3-uploader#226]
Hi, sorry in advance; I'm pretty new to web development.
I have a nodejs server running, and every time an image is uploaded by the client I would like to notify the server of the image URL so it can store it in a postgresql database. How would I go about doing this?

**Comment by mgadikota-rpx** [comment]
@pmazumder3927 : You need to make use of `onFinish` callback and notify server about the file/image upload.
