### ISSUE TITLE
Re initialize the component when onFinish 

### ISSUE THREAD

**Issue by StanBoyet** [odysseyscience/react-s3-uploader#26]
Hi guys,

I've been successful in integrating your module (awesome work, thanks :+1:).
With the `onFinish(signResult)` method I render another component, to show the uploaded file, as it's part of a form. What I'd like to know is if there is a way to "clean" the ReactS3Uploader component when upload is finished, to not display the filename anymore.

Thanks again,

**Comment by seanadkinson** [comment]
Hmm, it's just a `<input type="file"/>` that is rendered.  Are you wanting the entire thing to be hidden?  Or just the field to be cleared out?

If you want it to be hidden, I'd recommend just use a normal `state` flag to not render the component.

If you want it to be cleared out, we may want to add a component method that allows that, but I'd imagine you probably just want to hide it.

Am I understanding correctly?  Let me know if not, thanks!

**Comment by StanBoyet** [comment]
Hi Sean, thanks for your answer.
Yes, what I meant was the input to be cleared after upload. Sorry, my question was really unclear :)

**Comment by seanadkinson** [comment]
I just pushed a branch up called `clear-input`.  Can you check it out and see if it works for your purposes?  I'm not able to run it to test at the moment.

The branch adds a `clear` method to the `ReactS3Uploader` component.

So if you have this in a parent component:

    <ReactS3Uploader ref="uploader" ... />

Then you should be able to clear with:

    this.refs.uploader.clear();

I believe you can just add this to your `package.json` to see if it works for you:

    react-s3-uploader: 'git://github.com/odysseyscience/react-s3-uploader#clear-input'

If all looks good (and you don't mind testing on a couple browsers) I'll merge and release an update.

**Comment by 9o** [comment]
:+1: Looks good

**Comment by seanadkinson** [comment]
Pushed `v1.1.17` to npm, which includes the `clear` method.
