### ISSUE TITLE
"peerinvalid" npm problems

### ISSUE THREAD

**Issue by MattReimer** [odysseyscience/react-s3-uploader#29]
I packed this into my pull request and almost immediately regretted it:

I can't seem to get this module to live happily inside my `package.json` file:

```
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dropzone@2.2.1 wants react@>=0.13
npm ERR! peerinvalid Peer react-s3-uploader@1.1.16 wants react@*

npm ERR! Please include the following file with any support request:
npm ERR!     /some/dir/nar/GrandCanyon/GrainSizeCalculator/dgs-web/npm-debug.l
```

I can remove the lines 

```
  "peerDependencies": {
    "express": "4.x",
    "react": "*"
  },
```

and that seems to fix it but I'd love to know the "right" way to do it.

Cheers,

**Comment by MattReimer** [comment]
Just ignore me. It was an issue with react being at '0.14.2-beta3' and npm not being able to do math on that.

**Comment by seanadkinson** [comment]
Ah, got it.

I think we should move that `express` dependency to `optionalDependencies` though, since you don't have to use the express router.  But year, `react@*` should be required, and shouldn't cause any problems since it will accept any version.
