### ISSUE TITLE
Upgrade to ReactJS 0.14

### ISSUE THREAD

**Issue by riccardolorenzon** [odysseyscience/react-s3-uploader#31]
Hi, 
i upgraded my environment to React version 0.14. 
I can't use the uploader anymore, i think this depends from this instruction: 
```fileElement: this.getDOMNode() ``` because the exception i get is this:
```Warning: Unknown.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.```.

**Comment by seanadkinson** [comment]
Pretty easy to add a fill for this.  Will get a fix for this shortly.

**Comment by seanadkinson** [comment]
Pushed `v1.1.17` to npm

**Comment by riccardolorenzon** [comment]
Hi, 

thank you for the quick answer, 
BTW i still get ```React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.```

**Comment by seanadkinson** [comment]
Ah, that's right.  We'll need a full version bump to `v2` to support using `react-dom`.  I will probably get to that in the next month or so, as we'll be upgrading at my job.
