### ISSUE TITLE
SyntaxError with accentuated filenames

### ISSUE THREAD

**Issue by StanBoyet** [odysseyscience/react-s3-uploader#32]
Hi guys,

It seems that I have a problem with accentuated filenames (here, `3ème_étage.JPG`, :fr: people ... :grin: )

I don't quite know where to start. Is this react-s3-uploader related ? Or does it come from my Rails server ?

Thanks for the awesome work. We're rolling it in production in a few days :)

The error :

````
Uncaught SyntaxError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'inline; filename=3ème_étage.JPG' is not a valid HTTP header field value.S3Upload.uploadToS3 @ bundle.js?body=1:52653(anonymous function) @ bundle.js?body=1:52670(anonymous function) @ bundle.js?body=1:52610onReadyStateChangeReplacement @ includes.js?v=9db1f8db18400644bd5c7449e5295620:561
bundle.js?body=1:51078 Object {productType: Object, itemId: 1446286749503, options: Object, price: Object}
````

**Comment by StanBoyet** [comment]
My bad, I'm pretty sure it's because I don't escape them while getting the signed url from my server ...

**Comment by seanadkinson** [comment]
Must be [this line](https://github.com/odysseyscience/react-s3-uploader/blob/master/s3upload.js#L133) that is failing.

There must be restrictions on the encoding of characters for setting headers or something (I'm really not sure).  Looks like [this StackOverflow question](http://stackoverflow.com/questions/4400678/http-header-should-use-what-character-encoding) says that only US-ASCII characters are allowed.

I went looking at the jquery source code to see if they do anything special when setting request headers, and [here](https://github.com/jquery/jquery/blob/master/src/ajax.js#L470) where they take in the headers, and [here](https://github.com/jquery/jquery/blob/master/src/ajax/xhr.js#L68) where they set them, neither does any encoding.

You could try to `encodeURIComponents` on the filename, but not sure that would be correct.  If you come up with a solution, and want to submit a PR (or let me know what the solution is, and I can plug it in), we'd love to have it.

Thanks.

**Comment by StanBoyet** [comment]
This is basically what I'd like to implement, as I don't really want to decode/encode everytime either on server or client side.

http://stackoverflow.com/a/22935139/2726340

**Comment by seanadkinson** [comment]
Probably would need a PR for this.  Just need to do some extra work on this line: https://github.com/odysseyscience/react-s3-uploader/blob/master/s3upload.js#L63

**Comment by seanadkinson** [comment]
Pushed `v1.2.0` that addresses this issue.
