### ISSUE TITLE
Where to get data to validate file?

### ISSUE THREAD

**Issue by 9o** [odysseyscience/react-s3-uploader#33]
I'm having issues running client side and backend validation on the uploaded files, since I don't see anywhere in the component's api giving access to the files. How would this be achieved?

Thanks!

**Comment by seanadkinson** [comment]
What kind of data are you wanting to validate, and how?  If you are trying to validate the uploaded file, you would need to download the file from S3 and validate.  Make sense?  Let me know if I don't understand your use case.  Thanks.

**Comment by 9o** [comment]
I want to do something like explained here: http://stackoverflow.com/questions/8903854/check-image-width-and-height-on-upload-with-javascript

If I had access to the file, I could use a local URL of the image and, therefore, be able to validate it before uploading to s3.

**Comment by seanadkinson** [comment]
I see.  We had a [PR for adding files to callbacks](https://github.com/odysseyscience/react-s3-uploader/pull/30/files), but the author hasn't fixed it up yet.

I just created and pushed a branch named `callback-files` with the desired behavior from that PR.  Basically all the callbacks get the `file` as the last argument.

Try referencing this branch from your `package.json` like so:

    "react-s3-uploader": "odysseyscience/react-s3-uploader#callback-files"

Let me know if that gives you what you want, and I'll see about pushing an update.

**Comment by 9o** [comment]
The `callback-files` branch works perfectly. Thanks so much, Sean! :smile:

**Comment by seanadkinson** [comment]
Pushed `v1.1.18` with the changes.  Thanks for opening the issue.
