### ISSUE TITLE
S3Router "region" Option Updates and Uses Global aws-sdk Region Option

### ISSUE THREAD

**Issue by Kenny-House** [odysseyscience/react-s3-uploader#48]
As currently implemented, the `region` option in s3Router is passed to `aws.config.update()`: https://github.com/odysseyscience/react-s3-uploader/blob/6e3c62656c317fa8721762694b230fa41cc76965/s3router.js#L23

The `aws.config.update` function will update the global config object for the aws-sdk, meaning that any other service objects instantiated after s3Router will default to the region passed in the s3router options. 

Also, because of the way that s3router instantiates an s3object on each request, any changes to the global aws.config.region later could result in a different region being used than the one passed to s3router initially.

The AWS docs reference the global nature of the `aws.config` object specifically just below "Setting The Region" in the "Locking API Versions" section: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Setting_the_Region

The better option is to pass an object with the region setting directly to the s3 objects created by s3router. PR submitted: https://github.com/odysseyscience/react-s3-uploader/pull/47

**Comment by seanadkinson** [comment]
Thanks for PR.  Merged and published `v1.2.2` with this fix.
