### ISSUE TITLE
It seems not working on multiple language file name to upload.

### ISSUE THREAD

**Issue by realkyo** [odysseyscience/react-s3-uploader#58]
s3upload.js?d422:139 
Uncaught SyntaxError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'attachment; filename=中文測試.txt' is not a valid HTTP header field value.

**Comment by seanadkinson** [comment]
HTTP headers must be ASCII.  Are you using the latest version of the library?

Here is the line from a PR that addressed this issue: https://github.com/odysseyscience/react-s3-uploader/pull/45/files#diff-9e3d7fb482ae07f68196dd71048283ceR138

Can you make sure you are on the latest version, and see if the issue still happens?  Re-open if this is still an issue.  Thanks.
