### ISSUE TITLE
Question: Can I have the server specify the upload filename/folder?

### ISSUE THREAD

**Issue by javaguy** [odysseyscience/react-s3-uploader#61]
My scenario is I have a number of users who could upload files. I don't want them all going into the same folder, nor do I want to use the user submitted filenames. I'd rather make a request to the server which will then provide the right path to upload the file to based on the user.

Is that possible with this component?

Thanks,
Punit

**Comment by seanadkinson** [comment]
Yep, that is possible.

The backend `/s3/sign` call determines the S3 path to PUT the file, so if you have a custom implementation, you can just return the correct path for the user.

If you are using the builtin `s3router`, you can provide an optional `getFileKeyDir` function which takes in the `req` and returns basically a path prefix for S3.  A trailing slash is always added to the return value of this function (unless nothing is returned).

For example, if you wanted to put all uploads in a `uploads/{userId}` folder, you could setup the router like this:

```
app.use('/s3', require('react-s3-uploader/s3router')({
    bucket: "MyS3Bucket",
    getFileKeyDir: function(req) {
        return 'users/' + req.user.id;
    }
}));
```

Let me know if that works for you.

**Comment by seanadkinson** [comment]
Closing for now.

**Comment by javaguy** [comment]
Thanks for the feedback Sean, I'll try this out and get back to you.

**Comment by zirho** [comment]
I think there is another way to do this.
`options.s3path` (not s3Path)
