### ISSUE TITLE
need help with issues in setting up react-s3-uploader in my react(UI)->nodeJS(backend) app..

### ISSUE THREAD

**Issue by vijay122** [odysseyscience/react-s3-uploader#63]
I am getting the below error in my Node.js service. My UI app( build with react, using react-s3-uploader) is running on port 3000.
error message in service below :
Origin:http://localhost:3000
{ [TimeoutError: Missing credentials in config]
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: Thu Apr 21 2016 21:49:50 GMT+0530 (India Standard Time),
  originalError:
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: Thu Apr 21 2016 21:49:50 GMT+0530 (India Standard Time),
     originalError:
      { message: 'Connection timed out after 1000ms',
        code: 'TimeoutError',
        time: Thu Apr 21 2016 21:49:50 GMT+0530 (India Standard Time) } } }
node.js service :
 var AWS = require('aws-sdk');
 AWS.config.loadFromPath('./config.json');
app.use('/s3', require('react-s3-uploader/s3router')({
    bucket: "pictureBucket",
    region: 'us-west-2', //optional
    headers: {'Access-Control-Allow-Origin': '*'}, // optional
    ACL: 'private' // this is default
}));

config.json:

{
 "accessKeyId": "xxxxx",
 "secretAccessKey":"yyyyy",
 "region": "xxxxx"
}

ui app:

  <ReactS3Uploader
    signingUrl="/s3/sign"
    accept="image/*"
    onProgress={this.onUploadProgress}
    onError={this.onUploadError}
    onFinish={this.onUploadFinish}
    signingUrlHeaders={{ "additional": "headers" }}
    signingUrlQueryParams={{ "additional": "query-params" }}
    uploadRequestHeaders={{ 'x-amz-acl': 'public-read' }}
    contentDisposition="auto"
    server="http://localhost:8000"/>

my service app is running on port 8000. why does node doesnt recognize the credentials from my config.json.
is there something to connect the AWS variable and the s3 bucket.

**Comment by seanadkinson** [comment]
Sounds like an issue with the `AWS` SDK.  Try removing the `react-s3-uploader`, and make a call using the `aws` object.  Does it have your credentials correctly?  If not, solve that problem first.  If it works without this library, and doesn't work **only** when you add this library, please reopen this issue.  This is very unlikely, however, since this code literally doesn't do anything with the `AWS.config`.
