### ISSUE TITLE
unorm normalize call could be done server-side

### ISSUE THREAD

**Issue by Kuzmin** [odysseyscience/react-s3-uploader#65]
I'm not sure that I've read the code properly, but it looks to me like we have a call to `unorm.nfc` to normalize the filename. I think that this code could be moved to the server-side? This would save the 140kb unorm library from being downloaded to the client, which I think would be a big improvement to this library.

Thanks!

**Comment by Kuzmin** [comment]
Once I read up on what unorm actually does, I realized that this is an incredibly stupid issue and I should feel bad. I'm sorry, I got too excited...

**Comment by seanadkinson** [comment]
Thanks for bringing it up though.  I didn't realize the library was 140kb... that's pretty absurd for just making sure the filenames are ASCII.  I'll put this on the back-burning for being improved.

**Comment by Kuzmin** [comment]
Yeah I made a fork [here](https://github.com/Kuzmin/react-s3-uploader) that uses lodash deburr (5kb) function to make sure we only keep latin-1 characters in the filename, and it seems to work fine for a Swedish audience (åäö). I'm not sure if there's edge cases with other languages that would be missed with this though.

**Comment by talbenbasat** [comment]
Hi @seanadkinson,

I still have problems with an hebrew charecters.
is it possible to run replace after the latinize and norm
`
replace(/[^a-z0-9\.]/gi,'')
`

**Comment by seanadkinson** [comment]
@talbenbasat I'm pretty sure you can replace the filename in one of the pre-processing hooks.  See this thread: https://github.com/odysseyscience/react-s3-uploader/pull/79

**Comment by talbenbasat** [comment]
Hi @seanadkinson,

Just did!
Thanks a lot :)
