### ISSUE TITLE
Uploaded file URL

### ISSUE THREAD

**Issue by jakubrohleder** [odysseyscience/react-s3-uploader#68]
Hi! I have just started using this plugin with Ruby on Rails backend. Everything seems to work fine for me, but I'm stuck on one thing.

I try to use the plugin for following scenario: 
- Client requests signed url from Server (works)
- Client uploads file to S3 (works)
- Clients sends form to Server with updated user.avatar_url

How to get the public url of the recently uploaded file?

**Comment by seanadkinson** [comment]
When the user requests a signed URL, your backend is providing the path to `PUT` the file to S3, so you should know how to build the public image URL from an image name, no?  So when you save the image to the backend, it can rebuild the public URL from the image name.

The bundled `s3router.js` file provides an endpoint for you to provide the image name, and it will redirect to the public URL.  You could do the same in your RoR code.

So what our application does is:

* Client provides image name, and asks for a location to `PUT` in S3
* Server prefixes the path to S3, signs the URL, and returns the data
* Client `PUT`s to S3
* Client sends image name to server for storage
* When request image, client provides image name to `/s3/img/{imageName}`
* Server prefixes `imageName` with path to S3, and sends a redirect (or simply proxies the image in some cases)

Does that make sense?

**Comment by seanadkinson** [comment]
Re-reading your question, I think I realize now that you are saying that you simply are `POST`-ing the form, using a normal browser form submission.  Is that correct?

If so, and as you probably noticed, I don't think this library is providing any useful `<input>` information for the backend in this case.

There is enough callbacks though, that probably what you should do is just create an `<input type="hidden"/>` with the necessary information using javascript, after the image has successfully loaded.

Let me know if that is helpful, of if I am just missing the point.

**Comment by jakubrohleder** [comment]
@seanadkinson Thanks for the answer. Actually in you answered my question in the first part :). This flow sound really reasonable. I've haven't notice an obvious fact that the file public url can be easily recreated from bucket name, region and file path.

Thanks a lot 👍
