### ISSUE TITLE
File type check not working

### ISSUE THREAD

**Issue by yagudaev** [odysseyscience/react-s3-uploader#71]
In the example code in the `readme` there is a `accept="image/*"` but it is never actually used by the react component.

**Comment by seanadkinson** [comment]
All props are passed down to the underlying `<input type="file">` here: https://github.com/odysseyscience/react-s3-uploader/blob/master/ReactS3Uploader.js#L59

In this case, `accept` is specific to the file input, which is who uses it.

Reopen if there is something else I'm not seeing.  Thanks!
