### ISSUE TITLE
Unknown props `signingUrl`, `onFinish`, `uploadRequestHeaders`, `contentDisposition`, `server` on <input> tag. Remove these props from the element.

### ISSUE THREAD

**Issue by alexprice91** [odysseyscience/react-s3-uploader#74]
The newest of React introduced this new working. Basically, can't tack on props to native dom elements.

More description:
https://fb.me/react-unknown-prop

**Comment by seanadkinson** [comment]
So we just need to strip out the ones being explicitly used?  That's lame.

Want to take a stab at a PR?

**Comment by alexprice91** [comment]
Yeah. Really lame. My guess is they don't want you to put some private data into the DOM.

Here is the PR: https://github.com/odysseyscience/react-s3-uploader/pull/75.

It works locally. I am using `Object.keys` which seems to work all the way back to IE11. The idea here is to strip out any props that `react-s3-uploader` recommended, but otherwise let the user put whatever other props they want.

**Comment by seanadkinson** [comment]
According to this it is supported all the way back to IE9: http://kangax.github.io/compat-table/es5/#test-Object.keys

So we should be good.

**Comment by seanadkinson** [comment]
Pushed `v3.2.1` after merging #75 

Thanks
