### ISSUE TITLE
Downloads on Chrome fail if filename has commas

### ISSUE THREAD

**Issue by eagsalazar** [odysseyscience/react-s3-uploader#76]
http://stackoverflow.com/questions/38320996/s3-downloading-images-with-comma-in-filename-results-in-neterr-response-heade

I'm trying to figure out how to fix the downloads but in the meantime it might make sense to transform the upload filename somehow so there are no commas.

**Comment by seanadkinson** [comment]
Need to add a comma to this line: https://github.com/odysseyscience/react-s3-uploader/blob/master/s3upload.js#L66

Take a stab at a PR?

Thanks!

**Comment by eagsalazar** [comment]
Actually, in my fork I'm just fixing it by setting the content disposition manually and quoting the filename.  That way it will work even for previously uploaded file which is a requirement for my purposes since we've already got tons of files with commas.   However:

[https://forums.aws.amazon.com/thread.jspa?threadID=235006](AWS Support)

Looks like there is a very recent bug in s3 where the ResponseContentDisposition parameter is being ignored.  Once that gets fixed maybe that is a better option?

**Comment by seanadkinson** [comment]
Makes sense.  I'll leave this open for now.
