### ISSUE TITLE
Question : How can I manually set filename?

### ISSUE THREAD

**Issue by Teerapat12** [odysseyscience/react-s3-uploader#78]
I am working on uploading profile image. I want to manually set my filename to their userId so that when the same user upload new profile image, it will replace the old one. I found how to set directory in #61 , but I still can't figure out how to manually set the filename. 

Thank you :)

**Comment by Teerapat12** [comment]
`<ReactS3Uploader
                    className = "upload-img-input-btn form-control center-block"
                    signingUrl="/api/s3/sign"
                    accept="image/*"
                    onProgress={this.onUploadProgress.bind(this)}
                    onError={this.onUploadError}
                    onFinish={this.onUploadFinish.bind(this)}
                    signingUrlHeaders={{ additional: 'Access-Control-Allow-Origin'}}
                    uploadRequestHeaders={{ 'x-amz-acl': 'public-read' }}
                    contentDisposition="auto"
                />`

This is my code on react side

**Comment by seanadkinson** [comment]
No functionality currently built to support this, but it can be easily added.  Just need to support an optional filekey modifier/processor function, which would let you change the filekey based on the session or whatnot.  Code would be plugged in right around here: https://github.com/odysseyscience/react-s3-uploader/blob/master/s3router.js#L69

I don't have time to build this right now, but if you want to take a stab at a PR, I'll be happy to merge and release.

**Comment by Teerapat12** [comment]
I can manually set it now. I also forked it. Don't know if I did it correctly though. haha 

Thank you again.

**Comment by seanadkinson** [comment]
Just released `v4.0.0` which changes the filename scrubbing logic, and provides a simple way to add custom scrub logic.  Check out the updated documentation if you still need this functionality.

Thanks
