### ISSUE TITLE
Failed to load resource: Method PUT is not allowed by Access-Control-Allow-Methods.

### ISSUE THREAD

**Issue by OKNoah** [odysseyscience/react-s3-uploader#81]
I am able to generate what looks like a valid signing url from my back-end, but after selecting a file this is what I see in the console:

```
Upload progress: 0% Waiting
Failed to load resource: Method PUT is not allowed by Access-Control-Allow-Methods.
XMLHttpRequest cannot load https://amazon.s3.endpoint/myKey?AWSAccessKeyId=myValidAcccessKey&Expires=1471656383&Signature=xYZpoaKUlgMjPdarhSaqu4AwCE0%3D. Method PUT is not allowed by Access-Control-Allow-Methods.
error – "XHR error"
```

I have spend a lot of time making sure the CORS settings on S3 and my back-end are correct, but no joy. I have tried this with both Amazon and an S3-compatible alternative, both with the same result.

Anything I can try?

**Comment by OKNoah** [comment]
Some weird CORS thing documented nowhere.

**Comment by seanadkinson** [comment]
Yeah, CORS can be weird sometimes.  Sounds like you just needed to set `Access-Control-Allow-Methods` correctly.

Side note: I've found that Chrome Canary provides really useful error messaging in their Network tab... way better than standard chrome.

**Comment by OKNoah** [comment]
Yeah, this was all CORS stuff on the side of the S3 hosts. Fixed now.

**Comment by abhimanusharma** [comment]
@OKNoah I am facing the same issue, Can you tell me the setting you did to resolve this issue?
