### ISSUE TITLE
Question: How does it manage to upload a handful of files at a time?

### ISSUE THREAD

**Issue by jackytck** [odysseyscience/react-s3-uploader#85]
```javascript
S3Upload.prototype.handleFileSelect = function(files) {
    var result = [];
    for (var i=0; i < files.length; i++) {
        var file = files[i];
        this.preprocess(file, function(processedFile){
          this.onProgress(0, 'Waiting', processedFile);
          result.push(this.uploadFile(processedFile));
          return result;
        }.bind(this));
    }
};
```
From the code snippet above, when a lot of files are selected, how does it manage to upload a maximum of N files at a time?

**Comment by seanadkinson** [comment]
Are you asking this question because you think it _should_ cap the concurrent uploads?  Or because it _does_ cap the concurrent uploads?

Allocating TCP connections is something that the browser manages.  I think most have found that six connections performs best.

**Comment by jackytck** [comment]
> because it does cap the concurrent uploads

I thought it would overwhelm the browser by opening too many connections.
Now I know it's automatically throttled by the browser and is capped at six connections by default. Thanks.

**Comment by seanadkinson** [comment]
Good to know it is throttled appropriate by the browser (I hadn't tested that yet).  Thanks for the question!
