### ISSUE TITLE
SignatureDoesNotMatch Error

### ISSUE THREAD

**Issue by tdavis1198** [odysseyscience/react-s3-uploader#9]
Using the latest version, created a simple test based on the readme.

I have valid credentials and tested them using the following express route:

    router.get('/test', function(req, res) {
        var params = {
            Bucket: S3_BUCKET,
            Key: getFileKeyDir(req) + '/' + req.params[0]
        };
        var s3 = new aws.S3();
        s3.listBuckets(function(error, data) {
            if (error) {
                console.log(error); // error is Response.error
            } else {
                console.log(data); // data is Response.data
                res.json(data);
            }
        });        
    });

However, calls to .../get/img/t.png

returns the signature error.

I have manually uploaded a file to the bucket and can view it using other 3rd party tools using the same credentials.

Any ideas?

Btw, i get the same error uploading.

**Comment by seanadkinson** [comment]
For `router.get('/test', ...)`, there would be no `req.params[0]`, but I guess you aren't even using the `params` variable above.

In this example you posted, you are just doing an `s3.listBuckets`, so if that doesn't work, I'm not sure what the issue could be.  Not sure this has anything to do with `react-s3-uploader` if you can't list buckets with this code.

It could be that you need to specify the `region`, but you may want to create an issue with `aws-sdk`.

**Comment by tdavis1198** [comment]
I think i figured out the problem. Looks like there is an undocumented option getFileKeyDir that needs to be set as follows

    app.use('/s3', require('react-s3-uploader/s3router')({
    	getFileKeyDir: function(req) {return("folder")},
        bucket: "bucket"
    }));

If getFileKeyDir is not set it defaults to a function that returns "."

This results in the Key param that is used in the getSignedUrl calls being set to "./<filename>"

The getSignedUrl call will then sign the url using that Key. However, the actual url that is used to GET the image will not have the "./" characters.So the URL's do not match, hence the signature matching error.

So, create at least one directory in the bucket, and have it as the return value in the getFileKeyDir function.

**Comment by seanadkinson** [comment]
Ah, good catch.  We should document that feature, but also return "" if not implemented.  Thanks for the research.

**Comment by seanadkinson** [comment]
Just put up a fix on branch `fix-getFilKeyDir`.  Can you try it out in your application and see if it works as expected?

Add this to your `package.json` to test the branch:

    ...
    "react-s3-uploader": "odysseyscience/react-s3-uploader#fix-getFilKeyDir",
    ...

Delete `node_modules/react-s3-uploader` first, then run `npm install`

If all looks good, I'll push an update to NPM.

**Comment by tdavis1198** [comment]
Works for me. Thanks

**Comment by seanadkinson** [comment]
Pushed version `v1.1.8`.  Thanks

**Comment by rankun203** [comment]
For those of you may encountered this problem, make sure your `stringToSign` responsed by aws is the same to the API calculated. 

Search for  `stringToSign` and put breakpoint there to debug.
