### ISSUE TITLE
Clear file input field

### ISSUE THREAD

**Issue by csm123** [odysseyscience/react-s3-uploader#92]
From my `preprocess` function, I'd like to clear the file input field if my checks fail. Right now, I can abort the upload by not calling `file(next)`, but I don't know of a way to clear the file input field so it's clear to the user that they need to select a different file.

**Comment by seanadkinson** [comment]
See code here: https://github.com/odysseyscience/react-s3-uploader/blob/master/ReactS3Uploader.js#L89

Reopen if you need additional guidance.  Thanks

**Comment by sravi4701** [comment]
How to use the abort function?
