### ISSUE TITLE
Invoke 'clear' method

### ISSUE THREAD

**Issue by xuan9230** [odysseyscience/react-s3-uploader#93]
Hi, thanks for the awesome component.

I noticed there's a method called `clear` in the `ReactS3Uploader.js`, but not exposed. Say I want to clear the input value to be null every time after uploading, how can I use that?

Many thanks!

**Comment by xuan9230** [comment]
Just figured out myself.  We can do 

<ReactS3Uploader ref={node => (this.node = node)} />

And in onFinish: this.node.clear();

This will clear out the input element. Not sure if this is a good practice, and is there a way of getting the input 'value' directly?

**Comment by seanadkinson** [comment]
That would be the correct way to call `clear`, yes.

You may be able to get the `value` from one of the event listeners, but perhaps exposing it would be good.  Take a stab at a PR if you like.

Thanks!

**Comment by iamshouvikmitra** [comment]
Hi @seanadkinson,
How do I use the same in a functional component?
