### ISSUE TITLE
manually start uploading

### ISSUE THREAD

**Issue by gex** [odysseyscience/react-s3-uploader#95]
hi,

i'd like to use a different button to start the uploading, how can i achieve this? i could interrupt the uploading in the preprocess hook but i don't know how to trigger it after that.

thanks!

**Comment by sniepoort** [comment]
+1 for this

**Comment by arvinsim** [comment]
I was surprised that this feature wasn't implemented since this is a very common use case. +1

**Comment by seanadkinson** [comment]
Didn't see that this issue had so many votes!  Yeah, it is totally a use-case we should support.  Scanning the code, it shouldn't be too hard to conditionally omit the listener on [this line](https://github.com/odysseyscience/react-s3-uploader/blob/master/ReactS3Uploader.js#L94), then just call [uploadFile](https://github.com/odysseyscience/react-s3-uploader/blob/master/ReactS3Uploader.js#L60) via a reference to the component.  Anyone want to take a stab at a PR?

**Comment by AustinGomez** [comment]
Very surprised you can't do this yet. +1

**Comment by seanadkinson** [comment]
I appreciate your input @AustinGomez and others. I don't currently use this library, and don't have a lot of spare time at the moment - I just merge PRs and try to make sure things aren't broken.  If anyone would like to provide this functionality, I'll be happy to review and merge.  I usually get new features merged and released within a few hours.  Thanks!

**Comment by LKozakewycz** [comment]
I'm currently playing with this and haven't yet had time to try it out but I have modified the following which I'm hoping for results.

```javascript
    propTypes: {
        signingUrl: PropTypes.string,
        getSignedUrl: PropTypes.func,
        preprocess: PropTypes.func,
        onProgress: PropTypes.func,
        onFinish: PropTypes.func,
        onError: PropTypes.func,
        signingUrlMethod: PropTypes.string,
        signingUrlHeaders: PropTypes.oneOfType([
          PropTypes.object,
          PropTypes.func
        ]),
        signingUrlQueryParams: PropTypes.oneOfType([
          PropTypes.object,
          PropTypes.func
        ]),
        signingUrlWithCredentials: PropTypes.bool,
        uploadRequestHeaders: PropTypes.object,
        contentDisposition: PropTypes.string,
        server: PropTypes.string,
        scrubFilename: PropTypes.func,
        s3path: PropTypes.string,
        inputRef: PropTypes.func,
        autoUpload: PropTypes.bool
    },

    getDefaultProps: function() {
        return {
            preprocess: function(file, next) {
                console.log('Pre-process: ' + file.name);
                next(file);
            },
            onProgress: function(percent, message) {
                console.log('Upload progress: ' + percent + '% ' + message);
            },
            onFinish: function(signResult) {
                console.log("Upload finished: " + signResult.publicUrl)
            },
            onError: function(message) {
                console.log("Upload error: " + message);
            },
            server: '',
            signingUrlMethod: 'GET',
            scrubFilename: function(filename) {
                return filename.replace(/[^\w\d_\-\.]+/ig, '');
            },
            s3path: '',
            autoUpload: true
        };
    },
```

and for getInputProps function...

```javascript
getInputProps: function() {
        // declare ref beforehand and filter out
        // `inputRef` by `ReactS3Uploader.propTypes`
        var additional = {
            type: 'file',
            ref: this.props.inputRef
        };

        if ( autoUpload ) {
            additional.onChange = this.uploadFile;
        }
```


Then presumably, using the below properties, you can prevent it from auto uploading and then use the ref to call the `uploadFile` function.

```javascript
<ReactS3Uploader
     autoUpload={false}
     ref={uploader => { this.uploader = uploader; }}
     ...
     />
```


This is what I'm trying... however I'm off to grab some sleep so I shall test this tomorrow.

**Comment by AustinGomez** [comment]
@LKozakewycz Thanks for this. Gladly awaiting your work 😄

**Comment by LKozakewycz** [comment]
@AustinGomez I've submitted a pull request with the necessary changes: #155 

From this, you can do something like the following:

```javascript
    constructor(props) {
        super(props);
        this.uploader = null;
        this.handleUpload = this.handleUpload.bind(this);
    }
    
    handleUpload() {
        this.uploader.uploadFile();
    }

    render() {
        return (
            <div>
                <ReactS3Uploader
                    autoUpload={false}
                    ref={uploader => { this.uploader = uploader; }}
                    ...
                    />
            
                <input type="button" value="Upload" onClick={this.handleUpload} />
            </div>
        )
    }
```

**Comment by seanadkinson** [comment]
Released `v.4.6.0` with `autoUpload={false}` support.
